//----------------------------------------------------------------------------//
// Generated by LegUp High-Level Synthesis Tool Version 4.0 (http://legup.org)
// Compiled: Sun Jul 26 12:56:54 2015
// University of Toronto
// For research and academic purposes only. Commercial use is prohibited.
// Please send bugs to: legup@eecg.toronto.edu
// Date: Sun Jul 23 15:50:14 2017
//----------------------------------------------------------------------------//

`define MEMORY_CONTROLLER_ADDR_SIZE 32
`define MEMORY_CONTROLLER_DATA_SIZE 64
// Number of RAM elements: 2
`define MEMORY_CONTROLLER_TAG_SIZE 9
// @.str11 = private unnamed_addr constant [10 x i8] c"lenna.png\00", align 1
`define TAG_g_str11 `MEMORY_CONTROLLER_TAG_SIZE'd2
`define TAG_g_str11_a {`TAG_g_str11, 23'd0}
//   %ipl_8_in_255 = alloca %struct._IplImage*, align 4
`define TAG_main_0_ipl_8_in_255 `MEMORY_CONTROLLER_TAG_SIZE'd3
`define TAG_main_0_ipl_8_in_255_a {`TAG_main_0_ipl_8_in_255, 23'd0}

// Turn off warning 'ignoring unsupported system task'
// altera message_off 10175

`timescale 1 ns / 1 ns
module top
	(
		clk,
		reset,
		start,
		finish,
		waitrequest,
		return_val
	);
input clk;
input reset;
input start;
output wire finish;
input waitrequest;
output wire [31:0] return_val;
wire memory_controller_waitrequest;
wire memory_controller_enable_a;
wire [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_a;
wire memory_controller_write_enable_a;
wire [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_in_a;
wire [1:0] memory_controller_size_a;
wire [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_out_a;

wire memory_controller_enable_b;
wire [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_b;
wire memory_controller_write_enable_b;
wire [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_in_b;
wire [1:0] memory_controller_size_b;
wire [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_out_b;

/* synthesis translate_off */
assign memory_controller_waitrequest = waitrequest;
/* synthesis translate_on */

memory_controller memory_controller_inst (
	.clk( clk ),
	.memory_controller_enable_a( memory_controller_enable_a ),
	.memory_controller_enable_b( memory_controller_enable_b ),
	.memory_controller_address_a( memory_controller_address_a ),
	.memory_controller_address_b( memory_controller_address_b ),
	.memory_controller_write_enable_a( memory_controller_write_enable_a ),
	.memory_controller_write_enable_b( memory_controller_write_enable_b ),
	.memory_controller_in_a( memory_controller_in_a ),
	.memory_controller_in_b( memory_controller_in_b ),
	.memory_controller_size_a( memory_controller_size_a ),
	.memory_controller_size_b( memory_controller_size_b ),
	.memory_controller_waitrequest( memory_controller_waitrequest ),
	.memory_controller_out_reg_a( memory_controller_out_a ),
	.memory_controller_out_reg_b( memory_controller_out_b )
);

main main_inst(
	.clk( clk ),
	.clk2x( clk2x ),
	.clk1x_follower( clk1x_follower ),
	.reset( reset ),
	.start( start ),
	.finish( finish ),
	.return_val( return_val ),
	.memory_controller_waitrequest(memory_controller_waitrequest),
	.memory_controller_enable_a(memory_controller_enable_a),
	.memory_controller_address_a(memory_controller_address_a),
	.memory_controller_write_enable_a(memory_controller_write_enable_a),
	.memory_controller_in_a(memory_controller_in_a),
	.memory_controller_size_a(memory_controller_size_a),
	.memory_controller_out_a(memory_controller_out_a),
	.memory_controller_enable_b(memory_controller_enable_b),
	.memory_controller_address_b(memory_controller_address_b),
	.memory_controller_write_enable_b(memory_controller_write_enable_b),
	.memory_controller_in_b(memory_controller_in_b),
	.memory_controller_size_b(memory_controller_size_b),
	.memory_controller_out_b(memory_controller_out_b)
);

endmodule

`timescale 1 ns / 1 ns
module memory_controller
(
	clk,
	memory_controller_address_a,
	memory_controller_address_b,
	memory_controller_enable_a,
	memory_controller_enable_b,
	memory_controller_write_enable_a,
	memory_controller_write_enable_b,
	memory_controller_in_a,
	memory_controller_in_b,
	memory_controller_size_a,
	memory_controller_size_b,
	memory_controller_waitrequest,
	memory_controller_out_reg_a,
	memory_controller_out_reg_b
);

parameter latency = 2;

parameter ram_latency = latency-1;

integer j;

input clk;
input memory_controller_waitrequest;
input [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_a;
input memory_controller_enable_a;
input memory_controller_write_enable_a;
input [64-1:0] memory_controller_in_a;
input [1:0] memory_controller_size_a;
output reg [64-1:0] memory_controller_out_reg_a;
reg [64-1:0] memory_controller_out_prev_a;
reg [64-1:0] memory_controller_out_a;

reg memory_controller_enable_reg_a;
input [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_b;
input memory_controller_enable_b;
input memory_controller_write_enable_b;
input [64-1:0] memory_controller_in_b;
input [1:0] memory_controller_size_b;
output reg [64-1:0] memory_controller_out_reg_b;
reg [64-1:0] memory_controller_out_prev_b;
reg [64-1:0] memory_controller_out_b;

reg memory_controller_enable_reg_b;

reg [3:0] str11_address_a;
reg [3:0] str11_address_b;
reg str11_write_enable_a;
reg str11_write_enable_b;
reg [7:0] str11_in_a;
reg [7:0] str11_in_b;
wire [7:0] str11_out_a;
wire [7:0] str11_out_b;

// @.str11 = private unnamed_addr constant [10 x i8] c"lenna.png\00", align 1
rom_dual_port str11 (
	.clk( clk ),
	.clken( !memory_controller_waitrequest ),
	.address_a( str11_address_a ),
	.address_b( str11_address_b ),
	.q_a( str11_out_a ),
	.q_b( str11_out_b)
);
defparam str11.width_a = 8;
defparam str11.width_b = 8;
defparam str11.widthad_a = 4;
defparam str11.widthad_b = 4;
defparam str11.numwords_a = 10;
defparam str11.numwords_b = 10;
defparam str11.latency = ram_latency;
defparam str11.init_file = "str11.mif";

reg [0:0] main_0_ipl_8_in_255_address_a;
reg [0:0] main_0_ipl_8_in_255_address_b;
reg main_0_ipl_8_in_255_write_enable_a;
reg main_0_ipl_8_in_255_write_enable_b;
reg [31:0] main_0_ipl_8_in_255_in_a;
reg [31:0] main_0_ipl_8_in_255_in_b;
wire [31:0] main_0_ipl_8_in_255_out_a;
wire [31:0] main_0_ipl_8_in_255_out_b;

//   %ipl_8_in_255 = alloca %struct._IplImage*, align 4
ram_dual_port main_0_ipl_8_in_255 (
	.clk( clk ),
	.clken( !memory_controller_waitrequest ),
	.address_a( main_0_ipl_8_in_255_address_a ),
	.address_b( main_0_ipl_8_in_255_address_b ),
	.wren_a( main_0_ipl_8_in_255_write_enable_a ),
	.wren_b( main_0_ipl_8_in_255_write_enable_b ),
	.data_a( main_0_ipl_8_in_255_in_a ),
	.data_b( main_0_ipl_8_in_255_in_b ),
	.byteena_a( 1'b1 ),
	.byteena_b( 1'b1 ),
	.q_a( main_0_ipl_8_in_255_out_a ),
	.q_b( main_0_ipl_8_in_255_out_b)
);
defparam main_0_ipl_8_in_255.width_a = 32;
defparam main_0_ipl_8_in_255.width_b = 32;
defparam main_0_ipl_8_in_255.widthad_a = 1;
defparam main_0_ipl_8_in_255.widthad_b = 1;
defparam main_0_ipl_8_in_255.width_be_a = 1;
defparam main_0_ipl_8_in_255.width_be_b = 1;
defparam main_0_ipl_8_in_255.numwords_a = 1;
defparam main_0_ipl_8_in_255.numwords_b = 1;
defparam main_0_ipl_8_in_255.latency = ram_latency;
wire [`MEMORY_CONTROLLER_TAG_SIZE-1:0] tag_a;
assign tag_a = memory_controller_address_a[`MEMORY_CONTROLLER_ADDR_SIZE-1:`MEMORY_CONTROLLER_ADDR_SIZE-`MEMORY_CONTROLLER_TAG_SIZE];
reg [2:0] prevAddr_a;
reg [1:0] prevSize_a;
reg [2:0] prevSize_a_and;

always @(posedge clk)
if (!memory_controller_waitrequest)
begin
	prevAddr_a <= memory_controller_address_a[2:0];
	prevSize_a <= memory_controller_size_a;
end
wire [`MEMORY_CONTROLLER_TAG_SIZE-1:0] tag_b;
assign tag_b = memory_controller_address_b[`MEMORY_CONTROLLER_ADDR_SIZE-1:`MEMORY_CONTROLLER_ADDR_SIZE-`MEMORY_CONTROLLER_TAG_SIZE];
reg [2:0] prevAddr_b;
reg [1:0] prevSize_b;
reg [2:0] prevSize_b_and;

always @(posedge clk)
if (!memory_controller_waitrequest)
begin
	prevAddr_b <= memory_controller_address_b[2:0];
	prevSize_b <= memory_controller_size_b;
end

reg [2:0] select_not_struct_a;

wire select_str11_a;
assign select_str11_a = (tag_a == `TAG_g_str11);
reg [ram_latency:0] select_str11_reg_a;
wire [7:0] memory_controller_str11_out_a;
assign memory_controller_str11_out_a = {8{ select_str11_reg_a[ram_latency]}} & str11_out_a;

wire select_main_0_ipl_8_in_255_a;
assign select_main_0_ipl_8_in_255_a = (tag_a == `TAG_main_0_ipl_8_in_255);
reg [ram_latency:0] select_main_0_ipl_8_in_255_reg_a;
wire [31:0] memory_controller_main_0_ipl_8_in_255_out_a;
assign memory_controller_main_0_ipl_8_in_255_out_a = {32{ select_main_0_ipl_8_in_255_reg_a[ram_latency]}} & main_0_ipl_8_in_255_out_a;

always @(*)
begin
	str11_address_a = memory_controller_address_a [4-1+0:0] & {4{select_str11_a}};
	str11_write_enable_a = memory_controller_write_enable_a & select_str11_a;
	str11_in_a [8-1:0] = memory_controller_in_a[8-1:0];

	main_0_ipl_8_in_255_address_a = memory_controller_address_a [1-1+2:2] & {1{select_main_0_ipl_8_in_255_a}};
	main_0_ipl_8_in_255_write_enable_a = memory_controller_write_enable_a & select_main_0_ipl_8_in_255_a;
	main_0_ipl_8_in_255_in_a [32-1:0] = memory_controller_in_a[32-1:0];

end
always @(*)
begin
	select_not_struct_a [2:0] = 3'b0 | {2{select_main_0_ipl_8_in_255_reg_a[ram_latency]}};
	if (prevAddr_a[2:0] & select_not_struct_a[2:0] != 0 && memory_controller_enable_a)
	begin
		$display("Error: memory address not aligned to ram word size!");
		$finish;
	end

	prevSize_a_and[0] = prevSize_a[1] | prevSize_a[0];
	prevSize_a_and[1] = prevSize_a[1];
	prevSize_a_and[2] = prevSize_a[1] & prevSize_a[0];
	if ((prevAddr_a & prevSize_a_and) != 0 && memory_controller_enable_a)
	begin
		$display("Error: memory address not aligned to ram word size!");
		$finish;
	end
	memory_controller_out_prev_a = memory_controller_out_reg_a & { 64{!memory_controller_enable_reg_a}};
	memory_controller_out_a = 1'b0 | memory_controller_out_prev_a | memory_controller_str11_out_a | memory_controller_main_0_ipl_8_in_255_out_a;
end

always @(posedge clk)
if (!memory_controller_waitrequest)
begin
memory_controller_out_reg_a <= memory_controller_out_a;
memory_controller_enable_reg_a <= memory_controller_enable_a;
end

always @(posedge clk)
if (!memory_controller_waitrequest)
for (j = 0; j < ram_latency; j=j+1)
begin
select_str11_reg_a[j+1] <= select_str11_reg_a[j];
select_main_0_ipl_8_in_255_reg_a[j+1] <= select_main_0_ipl_8_in_255_reg_a[j];
end
always @(*)
begin
select_str11_reg_a[0] <= select_str11_a;
select_main_0_ipl_8_in_255_reg_a[0] <= select_main_0_ipl_8_in_255_a;
end

reg [2:0] select_not_struct_b;

wire select_str11_b;
assign select_str11_b = (tag_b == `TAG_g_str11);
reg [ram_latency:0] select_str11_reg_b;
wire [7:0] memory_controller_str11_out_b;
assign memory_controller_str11_out_b = {8{ select_str11_reg_b[ram_latency]}} & str11_out_b;

wire select_main_0_ipl_8_in_255_b;
assign select_main_0_ipl_8_in_255_b = (tag_b == `TAG_main_0_ipl_8_in_255);
reg [ram_latency:0] select_main_0_ipl_8_in_255_reg_b;
wire [31:0] memory_controller_main_0_ipl_8_in_255_out_b;
assign memory_controller_main_0_ipl_8_in_255_out_b = {32{ select_main_0_ipl_8_in_255_reg_b[ram_latency]}} & main_0_ipl_8_in_255_out_b;

always @(*)
begin
	str11_address_b = memory_controller_address_b [4-1+0:0] & {4{select_str11_b}};
	str11_write_enable_b = memory_controller_write_enable_b & select_str11_b;
	str11_in_b [8-1:0] = memory_controller_in_b[8-1:0];

	main_0_ipl_8_in_255_address_b = memory_controller_address_b [1-1+2:2] & {1{select_main_0_ipl_8_in_255_b}};
	main_0_ipl_8_in_255_write_enable_b = memory_controller_write_enable_b & select_main_0_ipl_8_in_255_b;
	main_0_ipl_8_in_255_in_b [32-1:0] = memory_controller_in_b[32-1:0];

end
always @(*)
begin
	select_not_struct_b [2:0] = 3'b0 | {2{select_main_0_ipl_8_in_255_reg_b[ram_latency]}};
	if (prevAddr_b[2:0] & select_not_struct_b[2:0] != 0 && memory_controller_enable_b)
	begin
		$display("Error: memory address not aligned to ram word size!");
		$finish;
	end

	prevSize_b_and[0] = prevSize_b[1] | prevSize_b[0];
	prevSize_b_and[1] = prevSize_b[1];
	prevSize_b_and[2] = prevSize_b[1] & prevSize_b[0];
	if ((prevAddr_b & prevSize_b_and) != 0 && memory_controller_enable_b)
	begin
		$display("Error: memory address not aligned to ram word size!");
		$finish;
	end
	memory_controller_out_prev_b = memory_controller_out_reg_b & { 64{!memory_controller_enable_reg_b}};
	memory_controller_out_b = 1'b0 | memory_controller_out_prev_b | memory_controller_str11_out_b | memory_controller_main_0_ipl_8_in_255_out_b;
end

always @(posedge clk)
if (!memory_controller_waitrequest)
begin
memory_controller_out_reg_b <= memory_controller_out_b;
memory_controller_enable_reg_b <= memory_controller_enable_b;
end

always @(posedge clk)
if (!memory_controller_waitrequest)
for (j = 0; j < ram_latency; j=j+1)
begin
select_str11_reg_b[j+1] <= select_str11_reg_b[j];
select_main_0_ipl_8_in_255_reg_b[j+1] <= select_main_0_ipl_8_in_255_reg_b[j];
end
always @(*)
begin
select_str11_reg_b[0] <= select_str11_b;
select_main_0_ipl_8_in_255_reg_b[0] <= select_main_0_ipl_8_in_255_b;
end

endmodule 

`timescale 1 ns / 1 ns
module main
(
	clk,
	clk2x,
	clk1x_follower,
	reset,
	start,
	finish,
	memory_controller_waitrequest,
	memory_controller_enable_a,
	memory_controller_address_a,
	memory_controller_write_enable_a,
	memory_controller_in_a,
	memory_controller_size_a,
	memory_controller_out_a,
	memory_controller_enable_b,
	memory_controller_address_b,
	memory_controller_write_enable_b,
	memory_controller_in_b,
	memory_controller_size_b,
	memory_controller_out_b,
	return_val
);

parameter [4:0] LEGUP_0 = 5'd0;
parameter [4:0] LEGUP_F_main_BB__0_1 = 5'd1;
parameter [4:0] LEGUP_F_main_BB__0_3 = 5'd3;
parameter [4:0] LEGUP_F_main_BB__0_4 = 5'd4;
parameter [4:0] LEGUP_F_main_BB__3_5 = 5'd5;
parameter [4:0] LEGUP_F_main_BB__5_6 = 5'd6;
parameter [4:0] LEGUP_F_main_BB__5_7 = 5'd7;
parameter [4:0] LEGUP_F_main_BB__5_8 = 5'd8;
parameter [4:0] LEGUP_F_main_BB__5_10 = 5'd10;
parameter [4:0] LEGUP_F_main_BB__5_11 = 5'd11;
parameter [4:0] LEGUP_F_main_BB__5_12 = 5'd12;
parameter [4:0] LEGUP_F_main_BB__5_14 = 5'd14;
parameter [4:0] LEGUP_F_main_BB__5_16 = 5'd16;
parameter [8:0] tag_offset = 9'd0;
parameter [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] tag_addr_offset = {tag_offset, 23'd0};
parameter [4:0] LEGUP_function_call_2 = 5'd2;
parameter [4:0] LEGUP_function_call_9 = 5'd9;
parameter [4:0] LEGUP_function_call_13 = 5'd13;
parameter [4:0] LEGUP_function_call_15 = 5'd15;

input  clk;
input  clk2x;
input  clk1x_follower;
input  reset;
input  start;
output reg  finish;
input  memory_controller_waitrequest;
output reg  memory_controller_enable_a;
output reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_a;
output reg  memory_controller_write_enable_a;
output reg [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_in_a;
output reg [1:0] memory_controller_size_a;
input [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_out_a;
output reg  memory_controller_enable_b;
output reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_b;
output reg  memory_controller_write_enable_b;
output reg [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_in_b;
output reg [1:0] memory_controller_size_b;
input [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_out_b;
output reg [31:0] return_val;
reg [4:0] cur_state;
reg [4:0] next_state;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_0_1;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_0_1_reg;
reg  main_0_2;
reg  main_0_2_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_5_6;
reg [31:0] main_5_7;
reg [31:0] main_5_8;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_5_10;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_5_10_reg;
reg [31:0] main_5_11;
reg [31:0] main_5_12;
reg  cvLoadImage_start;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] cvLoadImage_arg_0;
reg [31:0] cvLoadImage_arg_1;
reg  cvLoadImage_finish_final;
reg  cvLoadImage_finish_reg;
wire  cvLoadImage_finish;
wire [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] cvLoadImage_return_val;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] cvLoadImage_return_val_reg;
reg  cvGetOptimalDFTSize_start;
reg [31:0] cvGetOptimalDFTSize_arg_0;
reg  cvGetOptimalDFTSize_finish_final;
reg  cvGetOptimalDFTSize_finish_reg;
wire  cvGetOptimalDFTSize_finish;
wire [31:0] cvGetOptimalDFTSize_return_val;
reg  cvReleaseImage_start;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] cvReleaseImage_arg_0;
reg  cvReleaseImage_finish_final;
reg  cvReleaseImage_finish_reg;
wire  cvReleaseImage_finish;


cvLoadImage cvLoadImage (
	.clk (clk),
	.clk2x (clk2x),
	.clk1x_follower (clk1x_follower),
	.reset (reset),
	.start (cvLoadImage_start),
	.finish (cvLoadImage_finish),
	.return_val (cvLoadImage_return_val),
	.arg_0 (cvLoadImage_arg_0),
	.arg_1 (cvLoadImage_arg_1)
);

defparam
	cvLoadImage.tag_offset = tag_offset;


cvGetOptimalDFTSize cvGetOptimalDFTSize (
	.clk (clk),
	.clk2x (clk2x),
	.clk1x_follower (clk1x_follower),
	.reset (reset),
	.start (cvGetOptimalDFTSize_start),
	.finish (cvGetOptimalDFTSize_finish),
	.return_val (cvGetOptimalDFTSize_return_val),
	.arg_0 (cvGetOptimalDFTSize_arg_0)
);

defparam
	cvGetOptimalDFTSize.tag_offset = tag_offset;


cvReleaseImage cvReleaseImage (
	.clk (clk),
	.clk2x (clk2x),
	.clk1x_follower (clk1x_follower),
	.reset (reset),
	.start (cvReleaseImage_start),
	.finish (cvReleaseImage_finish),
	.arg_0 (cvReleaseImage_arg_0)
);

defparam
	cvReleaseImage.tag_offset = tag_offset;


/* Unsynthesizable Statements */
always @(posedge clk)
	if (!memory_controller_waitrequest) begin
	/* main: %3*/
	/*   %4 = tail call i32 (i8*, ...)* @printf(i8* getelementptr inbounds ([50 x i8]* @.str12, i32 0, i32 0)) #3*/
	if ((cur_state == LEGUP_F_main_BB__3_5)) begin
		$write("\nERROR! Image not loaded. Check in main function\n");
	end
	/* main: %3*/
	/*   tail call void @exit(i32 -1) #4*/
	if ((cur_state == LEGUP_F_main_BB__3_5)) begin
		$finish;
	end
end
always @(posedge clk) begin
if (reset == 1'b1)
	cur_state <= LEGUP_0;
else if (memory_controller_waitrequest == 1'd1)
	cur_state <= cur_state;
else
	cur_state <= next_state;
end

always @(*)
begin
next_state = cur_state;
case(cur_state)  // synthesis parallel_case  
LEGUP_0:
	if ((start == 1'd1))
		next_state = LEGUP_F_main_BB__0_1;
LEGUP_F_main_BB__0_1:
		next_state = LEGUP_function_call_2;
LEGUP_F_main_BB__0_3:
		next_state = LEGUP_F_main_BB__0_4;
LEGUP_F_main_BB__0_4:
	if ((main_0_2_reg == 1'd1))
		next_state = LEGUP_F_main_BB__3_5;
	else if ((main_0_2_reg == 1'd0))
		next_state = LEGUP_F_main_BB__5_6;
LEGUP_F_main_BB__3_5:
		next_state = LEGUP_0;
LEGUP_F_main_BB__5_10:
		next_state = LEGUP_F_main_BB__5_11;
LEGUP_F_main_BB__5_11:
		next_state = LEGUP_F_main_BB__5_12;
LEGUP_F_main_BB__5_12:
		next_state = LEGUP_function_call_13;
LEGUP_F_main_BB__5_14:
		next_state = LEGUP_function_call_15;
LEGUP_F_main_BB__5_16:
		next_state = LEGUP_0;
LEGUP_F_main_BB__5_6:
		next_state = LEGUP_F_main_BB__5_7;
LEGUP_F_main_BB__5_7:
		next_state = LEGUP_F_main_BB__5_8;
LEGUP_F_main_BB__5_8:
		next_state = LEGUP_function_call_9;
LEGUP_function_call_13:
	if ((cvGetOptimalDFTSize_finish_final == 1'd1))
		next_state = LEGUP_F_main_BB__5_14;
LEGUP_function_call_15:
	if ((cvReleaseImage_finish_final == 1'd1))
		next_state = LEGUP_F_main_BB__5_16;
LEGUP_function_call_2:
	if ((cvLoadImage_finish_final == 1'd1))
		next_state = LEGUP_F_main_BB__0_3;
LEGUP_function_call_9:
	if ((cvGetOptimalDFTSize_finish_final == 1'd1))
		next_state = LEGUP_F_main_BB__5_10;
default:
	next_state = cur_state;
endcase

end
always @(*) begin
	/* main: %0*/
	/*   %1 = tail call %struct._IplImage* @cvLoadImage(i8* getelementptr inbounds ([10 x i8]* @.str11, i32 0, i32 0), i32 0) #3*/
		main_0_1 = cvLoadImage_return_val_reg;
end
always @(posedge clk) begin
	/* main: %0*/
	/*   %1 = tail call %struct._IplImage* @cvLoadImage(i8* getelementptr inbounds ([10 x i8]* @.str11, i32 0, i32 0), i32 0) #3*/
	if ((cur_state == LEGUP_function_call_2)) begin
		main_0_1_reg <= main_0_1;
		if (start == 1'b0 && ^(main_0_1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_0_1_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %0*/
	/*   %2 = icmp eq %struct._IplImage* %1, null*/
		main_0_2 = (main_0_1_reg == 0);
end
always @(posedge clk) begin
	/* main: %0*/
	/*   %2 = icmp eq %struct._IplImage* %1, null*/
	if ((cur_state == LEGUP_F_main_BB__0_3)) begin
		main_0_2_reg <= main_0_2;
		if (start == 1'b0 && ^(main_0_2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_0_2_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %5*/
	/*   %6 = getelementptr inbounds %struct._IplImage* %1, i32 0, i32 11*/
		main_5_6 = (main_0_1_reg + 44);
end
always @(*) begin
	/* main: %5*/
	/*   %7 = load i32* %6, align 4, !tbaa !5*/
		main_5_7 = memory_controller_out_a[31:0];
end
always @(*) begin
	/* main: %5*/
	/*   %8 = add nsw i32 %7, -1*/
		main_5_8 = (main_5_7 + -32'd1);
end
always @(*) begin
	/* main: %5*/
	/*   %10 = getelementptr inbounds %struct._IplImage* %1, i32 0, i32 10*/
		main_5_10 = (main_0_1_reg + 40);
end
always @(posedge clk) begin
	/* main: %5*/
	/*   %10 = getelementptr inbounds %struct._IplImage* %1, i32 0, i32 10*/
	if ((cur_state == LEGUP_F_main_BB__5_6)) begin
		main_5_10_reg <= main_5_10;
		if (start == 1'b0 && ^(main_5_10) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_5_10_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %5*/
	/*   %11 = load i32* %10, align 4, !tbaa !8*/
		main_5_11 = memory_controller_out_a[31:0];
end
always @(*) begin
	/* main: %5*/
	/*   %12 = add nsw i32 %11, -1*/
		main_5_12 = (main_5_11 + -32'd1);
end
always @(posedge clk) begin
	/* main: %0*/
	/*   %1 = tail call %struct._IplImage* @cvLoadImage(i8* getelementptr inbounds ([10 x i8]* @.str11, i32 0, i32 0), i32 0) #3*/
	if ((cur_state == LEGUP_F_main_BB__0_1)) begin
		cvLoadImage_start <= 1'd1;
		if (start == 1'b0 && ^(1'd1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvLoadImage_start"); $finish; end
	end
	if ((cur_state == LEGUP_function_call_2)) begin
		cvLoadImage_start <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvLoadImage_start"); $finish; end
	end
end
always @(posedge clk) begin
	/* main: %0*/
	/*   %1 = tail call %struct._IplImage* @cvLoadImage(i8* getelementptr inbounds ([10 x i8]* @.str11, i32 0, i32 0), i32 0) #3*/
	if ((cur_state == LEGUP_F_main_BB__0_1)) begin
		cvLoadImage_arg_0 <= `TAG_g_str11_a;
		if (start == 1'b0 && ^(`TAG_g_str11_a) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvLoadImage_arg_0"); $finish; end
	end
end
always @(posedge clk) begin
	/* main: %0*/
	/*   %1 = tail call %struct._IplImage* @cvLoadImage(i8* getelementptr inbounds ([10 x i8]* @.str11, i32 0, i32 0), i32 0) #3*/
	if ((cur_state == LEGUP_F_main_BB__0_1)) begin
		cvLoadImage_arg_1 <= 32'd0;
		if (start == 1'b0 && ^(32'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvLoadImage_arg_1"); $finish; end
	end
end
always @(*) begin
	cvLoadImage_finish_final = cvLoadImage_finish_reg;
end
always @(posedge clk) begin
	if ((reset | (cur_state == LEGUP_F_main_BB__0_1))) begin
		cvLoadImage_finish_reg <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvLoadImage_finish_reg"); $finish; end
	end
	if (cvLoadImage_finish) begin
		cvLoadImage_finish_reg <= 1'd1;
		if (start == 1'b0 && ^(1'd1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvLoadImage_finish_reg"); $finish; end
	end
end
always @(posedge clk) begin
	if ((reset | (cur_state == LEGUP_F_main_BB__0_1))) begin
		cvLoadImage_return_val_reg <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvLoadImage_return_val_reg"); $finish; end
	end
	if (cvLoadImage_finish) begin
		cvLoadImage_return_val_reg <= cvLoadImage_return_val;
		if (start == 1'b0 && ^(cvLoadImage_return_val) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvLoadImage_return_val_reg"); $finish; end
	end
end
always @(posedge clk) begin
	/* main: %5*/
	/*   %9 = tail call i32 @cvGetOptimalDFTSize(i32 %8) #3*/
	if ((cur_state == LEGUP_F_main_BB__5_8)) begin
		cvGetOptimalDFTSize_start <= 1'd1;
		if (start == 1'b0 && ^(1'd1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvGetOptimalDFTSize_start"); $finish; end
	end
	if ((cur_state == LEGUP_function_call_9)) begin
		cvGetOptimalDFTSize_start <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvGetOptimalDFTSize_start"); $finish; end
	end
	/* main: %5*/
	/*   %13 = tail call i32 @cvGetOptimalDFTSize(i32 %12) #3*/
	if ((cur_state == LEGUP_F_main_BB__5_12)) begin
		cvGetOptimalDFTSize_start <= 1'd1;
		if (start == 1'b0 && ^(1'd1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvGetOptimalDFTSize_start"); $finish; end
	end
	if ((cur_state == LEGUP_function_call_13)) begin
		cvGetOptimalDFTSize_start <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvGetOptimalDFTSize_start"); $finish; end
	end
end
always @(posedge clk) begin
	/* main: %5*/
	/*   %9 = tail call i32 @cvGetOptimalDFTSize(i32 %8) #3*/
	if ((cur_state == LEGUP_F_main_BB__5_8)) begin
		cvGetOptimalDFTSize_arg_0 <= main_5_8;
		if (start == 1'b0 && ^(main_5_8) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvGetOptimalDFTSize_arg_0"); $finish; end
	end
	/* main: %5*/
	/*   %13 = tail call i32 @cvGetOptimalDFTSize(i32 %12) #3*/
	if ((cur_state == LEGUP_F_main_BB__5_12)) begin
		cvGetOptimalDFTSize_arg_0 <= main_5_12;
		if (start == 1'b0 && ^(main_5_12) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvGetOptimalDFTSize_arg_0"); $finish; end
	end
end
always @(*) begin
	cvGetOptimalDFTSize_finish_final = cvGetOptimalDFTSize_finish_reg;
end
always @(posedge clk) begin
	if ((reset | (cur_state == LEGUP_F_main_BB__5_8))) begin
		cvGetOptimalDFTSize_finish_reg <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvGetOptimalDFTSize_finish_reg"); $finish; end
	end
	if (cvGetOptimalDFTSize_finish) begin
		cvGetOptimalDFTSize_finish_reg <= 1'd1;
		if (start == 1'b0 && ^(1'd1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvGetOptimalDFTSize_finish_reg"); $finish; end
	end
	if ((reset | (cur_state == LEGUP_F_main_BB__5_12))) begin
		cvGetOptimalDFTSize_finish_reg <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvGetOptimalDFTSize_finish_reg"); $finish; end
	end
	if (cvGetOptimalDFTSize_finish) begin
		cvGetOptimalDFTSize_finish_reg <= 1'd1;
		if (start == 1'b0 && ^(1'd1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvGetOptimalDFTSize_finish_reg"); $finish; end
	end
end
always @(posedge clk) begin
	/* main: %5*/
	/*   call void @cvReleaseImage(%struct._IplImage** %ipl_8_in_255) #3*/
	if ((cur_state == LEGUP_F_main_BB__5_14)) begin
		cvReleaseImage_start <= 1'd1;
		if (start == 1'b0 && ^(1'd1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvReleaseImage_start"); $finish; end
	end
	if ((cur_state == LEGUP_function_call_15)) begin
		cvReleaseImage_start <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvReleaseImage_start"); $finish; end
	end
end
always @(posedge clk) begin
	/* main: %5*/
	/*   call void @cvReleaseImage(%struct._IplImage** %ipl_8_in_255) #3*/
	if ((cur_state == LEGUP_F_main_BB__5_14)) begin
		cvReleaseImage_arg_0 <= `TAG_main_0_ipl_8_in_255_a;
		if (start == 1'b0 && ^(`TAG_main_0_ipl_8_in_255_a) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvReleaseImage_arg_0"); $finish; end
	end
end
always @(*) begin
	cvReleaseImage_finish_final = cvReleaseImage_finish_reg;
end
always @(posedge clk) begin
	if ((reset | (cur_state == LEGUP_F_main_BB__5_14))) begin
		cvReleaseImage_finish_reg <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvReleaseImage_finish_reg"); $finish; end
	end
	if (cvReleaseImage_finish) begin
		cvReleaseImage_finish_reg <= 1'd1;
		if (start == 1'b0 && ^(1'd1) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to cvReleaseImage_finish_reg"); $finish; end
	end
end
always @(posedge clk) begin
	if ((cur_state == LEGUP_0)) begin
		finish <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to finish"); $finish; end
	end
	/* main: %5*/
	/*   ret i32 0*/
	if ((cur_state == LEGUP_F_main_BB__5_16)) begin
		finish <= (memory_controller_waitrequest == 1'd0);
		if (start == 1'b0 && ^((memory_controller_waitrequest == 1'd0)) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to finish"); $finish; end
	end
end
always @(*) begin
	memory_controller_enable_a = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_enable_a = 1'd0;
	end
	/* main: %0*/
	/*   store %struct._IplImage* %1, %struct._IplImage** %ipl_8_in_255, align 4, !tbaa !1*/
	if ((cur_state == LEGUP_F_main_BB__0_3)) begin
		memory_controller_enable_a = 1'd1;
	end
	/* main: %5*/
	/*   %7 = load i32* %6, align 4, !tbaa !5*/
	if ((cur_state == LEGUP_F_main_BB__5_6)) begin
		memory_controller_enable_a = 1'd1;
	end
	/* main: %5*/
	/*   %11 = load i32* %10, align 4, !tbaa !8*/
	if ((cur_state == LEGUP_F_main_BB__5_10)) begin
		memory_controller_enable_a = 1'd1;
	end
end
always @(*) begin
	memory_controller_address_a = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_address_a = 1'd0;
	end
	/* main: %0*/
	/*   store %struct._IplImage* %1, %struct._IplImage** %ipl_8_in_255, align 4, !tbaa !1*/
	if ((cur_state == LEGUP_F_main_BB__0_3)) begin
		memory_controller_address_a = `TAG_main_0_ipl_8_in_255_a;
	end
	/* main: %5*/
	/*   %7 = load i32* %6, align 4, !tbaa !5*/
	if ((cur_state == LEGUP_F_main_BB__5_6)) begin
		memory_controller_address_a = main_5_6;
	end
	/* main: %5*/
	/*   %11 = load i32* %10, align 4, !tbaa !8*/
	if ((cur_state == LEGUP_F_main_BB__5_10)) begin
		memory_controller_address_a = main_5_10_reg;
	end
end
always @(*) begin
	memory_controller_write_enable_a = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_write_enable_a = 1'd0;
	end
	/* main: %0*/
	/*   store %struct._IplImage* %1, %struct._IplImage** %ipl_8_in_255, align 4, !tbaa !1*/
	if ((cur_state == LEGUP_F_main_BB__0_3)) begin
		memory_controller_write_enable_a = 1'd1;
	end
	/* main: %5*/
	/*   %7 = load i32* %6, align 4, !tbaa !5*/
	if ((cur_state == LEGUP_F_main_BB__5_6)) begin
		memory_controller_write_enable_a = 1'd0;
	end
	/* main: %5*/
	/*   %11 = load i32* %10, align 4, !tbaa !8*/
	if ((cur_state == LEGUP_F_main_BB__5_10)) begin
		memory_controller_write_enable_a = 1'd0;
	end
end
always @(*) begin
	memory_controller_in_a = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_in_a = 1'd0;
	end
	/* main: %0*/
	/*   store %struct._IplImage* %1, %struct._IplImage** %ipl_8_in_255, align 4, !tbaa !1*/
	if ((cur_state == LEGUP_F_main_BB__0_3)) begin
		memory_controller_in_a = main_0_1_reg;
	end
end
always @(*) begin
	memory_controller_size_a = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_size_a = 1'd0;
	end
	/* main: %0*/
	/*   store %struct._IplImage* %1, %struct._IplImage** %ipl_8_in_255, align 4, !tbaa !1*/
	if ((cur_state == LEGUP_F_main_BB__0_3)) begin
		memory_controller_size_a = 2'd2;
	end
	/* main: %5*/
	/*   %7 = load i32* %6, align 4, !tbaa !5*/
	if ((cur_state == LEGUP_F_main_BB__5_6)) begin
		memory_controller_size_a = 2'd2;
	end
	/* main: %5*/
	/*   %11 = load i32* %10, align 4, !tbaa !8*/
	if ((cur_state == LEGUP_F_main_BB__5_10)) begin
		memory_controller_size_a = 2'd2;
	end
end
always @(*) begin
	memory_controller_enable_b = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_enable_b = 1'd0;
	end
end
always @(*) begin
	memory_controller_address_b = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_address_b = 1'd0;
	end
end
always @(*) begin
	memory_controller_write_enable_b = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_write_enable_b = 1'd0;
	end
end
always @(*) begin
	memory_controller_in_b = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_in_b = 1'd0;
	end
end
always @(*) begin
	memory_controller_size_b = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_size_b = 1'd0;
	end
end
always @(posedge clk) begin
	if ((cur_state == LEGUP_0)) begin
		return_val <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to return_val"); $finish; end
	end
	/* main: %5*/
	/*   ret i32 0*/
	if ((cur_state == LEGUP_F_main_BB__5_16)) begin
		return_val <= 32'd0;
		if (start == 1'b0 && ^(32'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to return_val"); $finish; end
	end
end

endmodule 
module ram_dual_port
(
	clk,
	clken,
	address_a,
	address_b,
	wren_a,
	wren_b,
	data_a,
	data_b,
	byteena_a,
	byteena_b,
	q_a,
	q_b
);

parameter  width_a = 1'd0;
parameter  width_b = 1'd0;
parameter  widthad_a = 1'd0;
parameter  widthad_b = 1'd0;
parameter  numwords_a = 1'd0;
parameter  numwords_b = 1'd0;
parameter  init_file = "UNUSED.mif";
parameter  width_be_a = 1'd0;
parameter  width_be_b = 1'd0;
parameter  latency = 1;

input  clk;
input  clken;
input [(widthad_a-1):0] address_a;
input [(widthad_b-1):0] address_b;
output wire [(width_a-1):0] q_a;
output wire [(width_b-1):0] q_b;
reg [(width_a-1):0] q_a_wire;
reg [(width_b-1):0] q_b_wire;
input  wren_a;
input  wren_b;
input [(width_a-1):0] data_a;
input [(width_b-1):0] data_b;
// byte enable is unsupported by inferred RAMs
input [width_be_a-1:0] byteena_a;
input [width_be_b-1:0] byteena_b;

(* ramstyle = "no_rw_check", ram_init_file = init_file *) reg [width_a-1:0] ram[numwords_a-1:0];

/* synthesis translate_off */
integer i;
ALTERA_MF_MEMORY_INITIALIZATION mem ();
reg [8*256:1] ram_ver_file;
initial begin
	if (init_file == "UNUSED.mif")
    begin
		for (i = 0; i < numwords_a; i = i + 1)
			ram[i] = 0;
    end
	else
    begin
        // modelsim can't read .mif files directly. So use Altera function to
        // convert them to .ver files
        mem.convert_to_ver_file(init_file, width_a, ram_ver_file);
        $readmemh(ram_ver_file, ram);
    end
end
/* synthesis translate_on */

always @ (posedge clk)
if (clken)
begin // Port A
if (wren_a)
begin
    ram[address_a] <= data_a;
    q_a_wire <= {width_a{1'bX}};
end
else
    q_a_wire <= ram[address_a];
end
always @ (posedge clk)
if (clken)
begin // Port b
if (wren_b)
begin
    ram[address_b] <= data_b;
    q_b_wire <= {width_b{1'bX}};
end
else
    q_b_wire <= ram[address_b];
end



integer j;
reg [(width_a-1):0] q_a_reg[latency:1], q_b_reg[latency:1];

always @(*)
begin
   q_a_reg[1] <= q_a_wire;
   q_b_reg[1] <= q_b_wire;
end

always @(posedge clk)
if (clken)
begin
   for (j = 1; j < latency; j=j+1)
   begin
       q_a_reg[j+1] <= q_a_reg[j];
       q_b_reg[j+1] <= q_b_reg[j];
   end
end

assign q_a = (clken) ? q_a_reg[latency] : 0;
assign q_b = (clken) ? q_b_reg[latency] : 0;


endmodule
module rom_dual_port
(
	clk,
	clken,
	address_a,
	address_b,
	q_a,
	q_b
);

parameter  width_a = 1'd0;
parameter  width_b = 1'd0;
parameter  widthad_a = 1'd0;
parameter  widthad_b = 1'd0;
parameter  numwords_a = 1'd0;
parameter  numwords_b = 1'd0;
parameter  init_file = "UNUSED.mif";
parameter  latency = 1;

input  clk;
input  clken;
input [(widthad_a-1):0] address_a;
input [(widthad_b-1):0] address_b;
output wire [(width_a-1):0] q_a;
output wire [(width_b-1):0] q_b;
reg [(width_a-1):0] q_a_wire;
reg [(width_b-1):0] q_b_wire;

(* ramstyle = "no_rw_check", ram_init_file = init_file *) reg [width_a-1:0] ram[numwords_a-1:0];

/* synthesis translate_off */
integer i;
ALTERA_MF_MEMORY_INITIALIZATION mem ();
reg [8*256:1] ram_ver_file;
initial begin
	if (init_file == "UNUSED.mif")
    begin
		for (i = 0; i < numwords_a; i = i + 1)
			ram[i] = 0;
    end
	else
    begin
        // modelsim can't read .mif files directly. So use Altera function to
        // convert them to .ver files
        mem.convert_to_ver_file(init_file, width_a, ram_ver_file);
        $readmemh(ram_ver_file, ram);
    end
end
/* synthesis translate_on */

always @ (posedge clk)
if (clken)
begin
    q_a_wire <= ram[address_a];
    q_b_wire <= ram[address_b];
end



integer j;
reg [(width_a-1):0] q_a_reg[latency:1], q_b_reg[latency:1];

always @(*)
begin
   q_a_reg[1] <= q_a_wire;
   q_b_reg[1] <= q_b_wire;
end

always @(posedge clk)
if (clken)
begin
   for (j = 1; j < latency; j=j+1)
   begin
       q_a_reg[j+1] <= q_a_reg[j];
       q_b_reg[j+1] <= q_b_reg[j];
   end
end

assign q_a = (clken) ? q_a_reg[latency] : 0;
assign q_b = (clken) ? q_b_reg[latency] : 0;


endmodule
// Adding code from verilog file: ../../boards/Virtex6/ML605/top.v


module ML605 (
       USER_CLOCK,
	    KEY,
	    SW,	    
       LED,
       LEDG,
		UART_RXD,
		UART_TXD

	    );

   input USER_CLOCK;
   input [4:0] KEY;
   input [7:0] SW;
   output [7:0] LED;
   output [7:0] LEDG;
   wire CLOCK_50;

    input UART_RXD;
    output UART_TXD;    
	wire clk = CLOCK_50;
	wire go = ~KEY[1];



   wire 	reset = ~KEY[0];
   wire 	start;
   wire [31:0] 	return_val;
   reg  [31:0] 	return_val_reg;
   wire 	finish;
   wire [3:0]	state;
   
   reg [6:0]   hex0, hex1, hex2, hex3, hex4, hex5, hex6, hex7;

   assign CLOCK_50 = USER_CLOCK;
   assign LED = 0;
   
	always @ (*) begin
		hex7 <= return_val_reg[31:28];
		hex6 <= return_val_reg[27:24];
		hex5 <= return_val_reg[23:20];
		hex4 <= return_val_reg[19:16];
		hex3 <= return_val_reg[15:12];
		hex2 <= return_val_reg[11:8];
		hex1 <= return_val_reg[7:4];
		hex0 <= return_val_reg[3:0];
	end
assign UART_TXD = 1'b0;

    parameter s_WAIT = 3'b001, s_START = 3'b010, s_EXE = 3'b011,
                s_DONE = 3'b100;

    // state registers
    reg [3:0] y_Q, Y_D;

    assign LEDG[3:0] = y_Q;

    // next state
    always @(*)
    begin
        case (y_Q)
            s_WAIT: if (go) Y_D = s_START; else Y_D = y_Q;

            s_START: Y_D = s_EXE;

            s_EXE: if (!finish) Y_D = s_EXE; else Y_D = s_DONE;

            s_DONE: Y_D = s_DONE;

            default: Y_D = 3'bxxx;
        endcase
    end

    // current state
    always @(posedge clk)
    begin
        if (reset) // synchronous clear
            y_Q <= s_WAIT;
        else
            y_Q <= Y_D;
    end

    always @(posedge clk)
        if (y_Q == s_EXE && finish)
            return_val_reg <= return_val;
        else if (y_Q == s_DONE)
            return_val_reg <= return_val_reg;
        else
            return_val_reg <= 0;


    assign start = (y_Q == s_START);

   
   top top_inst (
      .clk (clk),
      .reset (reset),
      .finish (finish),
      .return_val (return_val),
        .start (start)

    );

   

endmodule

// Adding code from verilog file: ../../boards/StratixIV/DE4/top.v


module de4 ( 
    	     OSC_50_BANK2, 
             BUTTON, 
             LED, 
    	     SEG0_D, 
    	     SEG1_D 
	     ); 
   input OSC_50_BANK2; 
   input [1:0] BUTTON; 
   output [6:0] SEG0_D; 
   output [6:0] SEG1_D; 
   output [7:0] LED; 
   
   de2 de2_inst ( 
		  .CLOCK_50 (OSC_50_BANK2), 
		  .LEDG (LED), 
		  .KEY (BUTTON), 
		  .SW (), 
		  .HEX0 (SEG0_D), 
		  .HEX1 (SEG1_D), 
		  .HEX2 (), 
		  .HEX3 (), 
		  .HEX4 (), 
		  .HEX5 (), 
		  .HEX6 (), 
		  .HEX7 () 
		  ); 
   
endmodule
// Adding code from verilog file: ../../boards/CycloneII/DE2/top.v


module de2 (
	    CLOCK_50,
	    KEY,
	    SW,
	    HEX0,
	    HEX1,
	    HEX2,
	    HEX3,
	    HEX4,
	    HEX5,
	    HEX6,
	    HEX7,
	    LEDG,
		UART_RXD,
		UART_TXD

	    );

   input CLOCK_50;
   input [3:0] KEY;
   input [17:0] SW;
   output [6:0] HEX0, HEX1,  HEX2,  HEX3,  HEX4,  HEX5,  HEX6,  HEX7;
   reg [6:0] 	hex0, hex1, hex2, hex3, hex4, hex5, hex6, hex7;
   

   output [7:0] LEDG;
    input UART_RXD;
    output UART_TXD;    
	wire clk = CLOCK_50;
	wire go = ~KEY[1];



   wire 	reset = ~KEY[0];
   wire 	start;
   wire [31:0] 	return_val;
   reg  [31:0] 	return_val_reg;
   wire 	finish;
   wire [3:0]	state;

   hex_digits h7( .x(hex7), .hex_LEDs(HEX7));
   hex_digits h6( .x(hex6), .hex_LEDs(HEX6));
   hex_digits h5( .x(hex5), .hex_LEDs(HEX5));
   hex_digits h4( .x(hex4), .hex_LEDs(HEX4));
   hex_digits h3( .x(hex3), .hex_LEDs(HEX3));
   hex_digits h2( .x(hex2), .hex_LEDs(HEX2));
   hex_digits h1( .x(hex1), .hex_LEDs(HEX1));
   hex_digits h0( .x(hex0), .hex_LEDs(HEX0));
   
	always @ (*) begin
		hex7 <= return_val_reg[31:28];
		hex6 <= return_val_reg[27:24];
		hex5 <= return_val_reg[23:20];
		hex4 <= return_val_reg[19:16];
		hex3 <= return_val_reg[15:12];
		hex2 <= return_val_reg[11:8];
		hex1 <= return_val_reg[7:4];
		hex0 <= return_val_reg[3:0];
	end
assign UART_TXD = 1'b0;

    parameter s_WAIT = 3'b001, s_START = 3'b010, s_EXE = 3'b011,
                s_DONE = 3'b100;

    // state registers
    reg [3:0] y_Q, Y_D;

    assign LEDG[3:0] = y_Q;

    // next state
    always @(*)
    begin
        case (y_Q)
            s_WAIT: if (go) Y_D = s_START; else Y_D = y_Q;

            s_START: Y_D = s_EXE;

            s_EXE: if (!finish) Y_D = s_EXE; else Y_D = s_DONE;

            s_DONE: Y_D = s_DONE;

            default: Y_D = 3'bxxx;
        endcase
    end

    // current state
    always @(posedge clk)
    begin
        if (reset) // synchronous clear
            y_Q <= s_WAIT;
        else
            y_Q <= Y_D;
    end

    always @(posedge clk)
        if (y_Q == s_EXE && finish)
            return_val_reg <= return_val;
        else if (y_Q == s_DONE)
            return_val_reg <= return_val_reg;
        else
            return_val_reg <= 0;


    assign start = (y_Q == s_START);

   
   top top_inst (
      .clk (clk),
      .reset (reset),
      .finish (finish),
      .return_val (return_val),
        .start (start)

    );

endmodule

module circuit_start_control (
    go,
    control_key
);
    input control_key;
    output go;
    assign go = control_key;
endmodule
module hex_digits(x, hex_LEDs);
    input [3:0] x;
    output [6:0] hex_LEDs;
    
    assign hex_LEDs[0] = (~x[3] & ~x[2] & ~x[1] & x[0]) |
                            (~x[3] & x[2] & ~x[1] & ~x[0]) |
                            (x[3] & x[2] & ~x[1] & x[0]) |
                            (x[3] & ~x[2] & x[1] & x[0]);
    assign hex_LEDs[1] = (~x[3] & x[2] & ~x[1] & x[0]) |
                            (x[3] & x[1] & x[0]) |
                            (x[3] & x[2] & ~x[0]) |
                            (x[2] & x[1] & ~x[0]);
    assign hex_LEDs[2] = (x[3] & x[2] & ~x[0]) |
                            (x[3] & x[2] & x[1]) |
                            (~x[3] & ~x[2] & x[1] & ~x[0]);
    assign hex_LEDs[3] = (~x[3] & ~x[2] & ~x[1] & x[0]) | 
                            (~x[3] & x[2] & ~x[1] & ~x[0]) | 
                            (x[2] & x[1] & x[0]) | 
                            (x[3] & ~x[2] & x[1] & ~x[0]);
    assign hex_LEDs[4] = (~x[3] & x[0]) |
                            (~x[3] & x[2] & ~x[1]) |
                            (~x[2] & ~x[1] & x[0]);
    assign hex_LEDs[5] = (~x[3] & ~x[2] & x[0]) | 
                            (~x[3] & ~x[2] & x[1]) | 
                            (~x[3] & x[1] & x[0]) | 
                            (x[3] & x[2] & ~x[1] & x[0]);
    assign hex_LEDs[6] = (~x[3] & ~x[2] & ~x[1]) | 
                            (x[3] & x[2] & ~x[1] & ~x[0]) | 
                            (~x[3] & x[2] & x[1] & x[0]);
    
endmodule
`timescale 1 ns / 1 ns
module main_tb
(
);

reg  clk;
reg  reset;
reg  start;
reg  waitrequest;
wire [31:0] return_val;
wire  finish;


top top_inst (
	.clk (clk),
	.reset (reset),
	.start (start),
	.waitrequest (waitrequest),
	.finish (finish),
	.return_val (return_val)
);




initial 
    clk = 0;
always @(clk)
    clk <= #10 ~clk;

initial begin
//$monitor("At t=%t clk=%b %b %b %b %d", $time, clk, reset, start, finish, return_val);
@(negedge clk);
reset <= 1;
@(negedge clk);
reset <= 0;
start <= 1;
@(negedge clk);
start <= 0;
end

always@(finish) begin
    if (finish == 1) begin
        $display("At t=%t clk=%b finish=%b return_val=%d", $time, clk, finish, return_val);
        $display("Cycles: %d", ($time-50)/20);
        $finish;
    end
end

initial begin
waitrequest <= 1;
@(negedge clk);
@(negedge clk);
waitrequest <= 0;
end


endmodule 
